# Colors
colors_init="\e[" # Initialization

## Options
txt_regul="${colors_init}0"
txt_bold="${colors_init}1"

## Base colors
color_red=";31m"
color_green=";32m"
color_yellow=";33m"
color_blue=";34m"
color_purple=";35m"
color_white=";37m"

colors_end="${txt_regul}m" # RESET-END COLORS

## Bold text colors
col_txt_bld_red="${txt_bold}${color_red}"
col_txt_bld_grn="${txt_bold}${color_green}"
col_txt_bld_ylw="${txt_bold}${color_yellow}"
col_txt_bld_blu="${txt_bold}${color_blue}"
col_txt_bld_pur="${txt_bold}${color_purple}"
col_txt_bld_wht="${txt_bold}${color_white}"

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
	*i*)
		;;
	*)
		return
		;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTFILE=~/.bash_history
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/usr/bin/sh lesspipe)"


# Configuración de prompt
# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
	debian_chroot=$(/usr/bin/cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
	xterm-color|*-256color)
		color_prompt=yes
		;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
	if [ -x /usr/bin/tput ] && /usr/bin/tput setaf 1 >&/dev/null; then
		# We have color support; assume it's compliant with Ecma-48
		# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
		# a case would tend to support setf rather than setaf.)
		color_prompt=yes
	else
		color_prompt=
	fi
fi

## Usar starship
eval "$(/usr/bin/starship init bash)"

## Prompt para debian, ubuntu, etc.
if [ "$color_prompt" = yes ]; then
	PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
	PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

## Prompt estilo centos, fedora, arch, etc.
#if [ $EUID -eq 0 ]; then
#	export PS1="${col_txt_bld_blu}[${col_txt_bld_wht}\u@\H ${col_txt_bld_pur}\w${col_txt_bld_blu}] ${col_txt_bld_red}# ${colors_end}"
#else
#	export PS1="${col_txt_bld_blu}[${col_txt_bld_wht}\u@\H ${col_txt_bld_pur}\w${col_txt_bld_blu}] ${col_txt_bld_grn}\$ ${colors_end}"
#fi

## Generic prompt for non specific distribution type
#if [ $EUID -eq 0 ]; then
#	PS1="${col_txt_bld_red}\u@\h:${col_txt_bld_blu}\w${col_txt_bld_wht}# ${colors_end}"
#else
#	PS1="${col_txt_bld_ylw}\u@\h:${col_txt_bld_blu}\w${col_txt_bld_wht}\$ ${colors_end}"
#fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
	xterm*|rxvt*)
		PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
		;;
	*)
		;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(/usr/bin/dircolors -b ~/.dircolors)" || eval "$(/usr/bin/dircolors -b)"
	alias ls='/usr/bin/ls -CF --color=auto'
	alias dir='/usr/bin/dir --color=auto'
	alias vdir='/usr/bin/vdir --color=auto'

	alias grep='/usr/bin/grep --color=auto'
	alias fgrep='/usr/bin/fgrep --color=auto'
	alias egrep='/usr/bin/egrep --color=auto'
fi

## Colores de advertencias y errores para comando 'gcc' 
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

## Colores para comando 'ip'
alias ip='/usr/bin/ip --color=auto'

## Colores para comando 'man'
function man() {
	/usr/bin/env \
	LESS_TERMCAP_mb=$(echo -e "${col_txt_bld_red}") \
	LESS_TERMCAP_md=$(echo -e "${col_txt_bld_red}") \
	LESS_TERMCAP_me=$(echo -e "${colors_end}") \
	LESS_TERMCAP_se=$(echo -e "${colors_end}") \
	LESS_TERMCAP_so=$(echo -e "${col_txt_bld_ylw}") \
	LESS_TERMCAP_ue=$(echo -e "${colors_end}") \
	LESS_TERMCAP_us=$(echo -e "${col_txt_bld_grn}") \
	man "$@"
}

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

## Custom
alias vi='/usr/bin/nvim'
alias vim='/usr/bin/nvim'

if command -v bat >/dev/null 2>&1; then
    alias cat='/usr/bin/bat'
    alias catn='/usr/bin/bat --style=plain'
    alias catp='/usr/bin/bat --paging=never'
    alias catnp='/usr/bin/bat --style=plain --paging=never'
elif command -v batcat >/dev/null 2>&1; then
    alias cat='/usr/bin/batcat'
    alias catn='/usr/bin/batcat --style=plain'
    alias catp='/usr/bin/batcat --paging=never'
    alias catnp='/usr/bin/batcat --style=plain --paging=never'
else
    : # Nada
fi

if command -v lsd >/dev/null 2>&1; then
	alias ls='/usr/bin/lsd -F --group-directories-first --color=auto'
	alias ll='/usr/bin/lsd -lF --group-directories-first --color=auto'
	alias la='/usr/bin/lsd -AF --group-directories-first --color=auto'
	alias lla='/usr/bin/lsd -lAF --group-directories-first --color=auto'
else
	alias ls='/usr/bin/ls -CF --group-directories-first --color=auto'
	alias ll='/usr/bin/ls -lCF --group-directories-first --color=auto'
	alias la='/usr/bin/ls -ACF --group-directories-first --color=auto'
	alias lla='/usr/bin/ls -lACF --group-directories-first --color=auto'
fi

alias bashrconfig="/usr/bin/nvim ~/.bashrc"

alias cp="/bin/cp -i"
alias mv="/bin/mv -i"
alias rm="/bin/rm -I"
alias history="history 0"

alias ll='ls -lCF'
alias la='ls -ACF'
alias lla='ls -lACF'

# PATH
main_user="marcvs"
wanted_paths=(
    "/usr/local/sbin"
    "/usr/local/bin"
    "/usr/sbin"
    "/usr/bin"
    "/sbin"
    "/bin"
    "/snap/bin"
    "/opt/bin"
    "/root/.local/bin"
	"/usr/games"
	"/usr/local/games"
	"/usr/share/games"
	"/usr/sandbox"
    "/home/$main_user/.local/bin"
)

for path_to_add in "${wanted_paths[@]}"; do
    # Comprobar si el directorio existe y si NO está ya en el PATH
    if [ -d "$path_to_add" ] && [[ ":$PATH:" != *":$path_to_add:"* ]]; then
        export PATH="$PATH:$path_to_add"
    fi
done

## fzf
FZF_PATH="/home/$main_user/.fzf/bin"
if [ -d "$FZF_PATH" ]; then
	export PATH="$FZF_PATH:$PATH"
	[ -f ~/.fzf.bash ] && source ~/.fzf.bash
elif command -v fzf &> /dev/null; then
	eval "$(fzf --bash)"
else
    : # Nada
fi

## fnm
FNM_PATH="/home/$main_user/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
	export PATH="$FNM_PATH:$PATH"
	eval "`fnm env`"
else
    : # Nada
fi

# Funciones cutom
## Formato de 'PS Credential' de Windows
function ps_credential() {
	if command -v bat >/dev/null 2>&1; then
		/usr/bin/bat -l powershell --paging=never /opt/help/pscredential
	elif command -v batcat >/dev/null 2>&1; then
		/usr/bin/batcat -l powershell --paging=never /opt/help/pscredential
	else
		/usr/bin/cat /opt/help/pscredential
	fi
}

## Comandos para persistencia en Windows
function persistence() {
	if command -v bat >/dev/null 2>&1; then
		/usr/bin/bat -l cmd --paging=never /opt/help/persistence
	elif command -v batcat >/dev/null 2>&1; then
		/usr/bin/batcat -l cmd --paging=never /opt/help/persistence
	else
		/usr/bin/cat /opt/help/persistence
	fi
}

## Comandos para crear certificados digitales
function create_cert() {
	if command -v bat >/dev/null 2>&1; then
		/usr/bin/bat -l bash --paging=never /opt/help/createcert
	elif command -v batcat >/dev/null 2>&1; then
		/usr/bin/batcat -l bash --paging=never /opt/help/createcert
	else
		/usr/bin/cat /opt/help/createcert
	fi
}

## Escanear redes Wi-Fi cercanas
function wifi_scan() {
	/usr/bin/nmcli dev wifi list
}

## Connectars a Wi-Fi con y sin contraseña
function wifi_connect() {
	if [ $2 ]; then
		/usr/bin/nmcli dev wifi connect $1 password $2
	elif [ !$2 ]; then
		/usr/bin/nmcli dev wifi connect $1
	fi
}