# Colors
declare -r colors_init="\e[" # Initialization

## Options
declare -r txt_regul="${colors_init}0"
declare -r txt_bold="${colors_init}1"

## Base colors
declare -r color_red=";31m"
declare -r color_green=";32m"
declare -r color_yellow=";33m"
declare -r color_blue=";34m"
declare -r color_purple=";35m"
declare -r color_white=";37m"

declare -r colors_end="${txt_regul}m" # RESET-END COLORS

## Bold text colors
declare -r col_txt_bld_red="${txt_bold}${color_red}"
declare -r col_txt_bld_grn="${txt_bold}${color_green}"
declare -r col_txt_bld_ylw="${txt_bold}${color_yellow}"
declare -r col_txt_bld_blu="${txt_bold}${color_blue}"
declare -r col_txt_bld_pur="${txt_bold}${color_purple}"
declare -r col_txt_bld_wht="${txt_bold}${color_white}"

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
	*i*)
		;;
	*)
		return
		;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTFILE=~/.bash_history
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/usr/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
	debian_chroot=$(/usr/bin/cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
	xterm-color|*-256color)
		color_prompt=yes
		;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
	if [ -x /usr/bin/tput ] && /usr/bin/tput setaf 1 >&/dev/null; then
		# We have color support; assume it's compliant with Ecma-48
		# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
		# a case would tend to support setf rather than setaf.)
		color_prompt=yes
	else
		color_prompt=
	fi
fi

# PROMPT CONFIGURATION
## Use starship
#eval "$(/usr/bin/starship init bash)"

## Prompt for debian, ubuntu, etc.
if [ "$color_prompt" = yes ]; then
	PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
	PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

## Prompt for centos, fedora, arch, etc.
#if [ $EUID -eq 0 ]; then
#	export PS1="${col_txt_bld_blu}[${col_txt_bld_wht}\u@\H ${col_txt_bld_pur}\w${col_txt_bld_blu}] ${col_txt_bld_red}# ${colors_end}"
#else
#	export PS1="${col_txt_bld_blu}[${col_txt_bld_wht}\u@\H ${col_txt_bld_pur}\w${col_txt_bld_blu}] ${col_txt_bld_grn}\$ ${colors_end}"
#fi

## Generic prompt for non specific distribution type
#if [ $EUID -eq 0 ]; then
#	PS1="${col_txt_bld_red}\u@\h:${col_txt_bld_blu}\w${col_txt_bld_wht}# ${colors_end}"
#else
#	PS1="${col_txt_bld_ylw}\u@\h:${col_txt_bld_blu}\w${col_txt_bld_wht}\$ ${colors_end}"
#fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
	xterm*|rxvt*)
		PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
		;;
	*)
		;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(/usr/bin/dircolors -b ~/.dircolors)" || eval "$(/usr/bin/dircolors -b)"
	alias ls='/usr/bin/ls -CF --color=auto'
	alias dir='/usr/bin/dir --color=auto'
	alias vdir='/usr/bin/vdir --color=auto'

	alias grep='/usr/bin/grep --color=auto'
	alias fgrep='/usr/bin/fgrep --color=auto'
	alias egrep='/usr/bin/egrep --color=auto'
fi

# Some more 'ls' aliases
alias ll='ls -lCF'
alias la='ls -ACF'
alias lla='ls -lACF'

# Set colors
## Colored 'gcc' warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

## Colored 'ip' command
alias ip='/usr/bin/ip --color=auto'

## Set 'man' colors
function man() {
	/usr/bin/env \
	LESS_TERMCAP_mb=$(echo -e "${col_txt_bld_red}") \
	LESS_TERMCAP_md=$(echo -e "${col_txt_bld_red}") \
	LESS_TERMCAP_me=$(echo -e "${colors_end}") \
	LESS_TERMCAP_se=$(echo -e "${colors_end}") \
	LESS_TERMCAP_so=$(echo -e "${col_txt_bld_ylw}") \
	LESS_TERMCAP_ue=$(echo -e "${colors_end}") \
	LESS_TERMCAP_us=$(echo -e "${col_txt_bld_grn}") \
	man "$@"
}

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

export PATH=/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/snap/bin:/usr/games:/usr/local/games:/usr/share/games:/usr/sandbox:/root/.local/bin:/opt/bin
