#!/usr/bin/bash

/usr/bin/pgrep -x sxhkd > /dev/null || /usr/bin/sxhkd &

#/usr/bin/xrandr -s 0
#if [ -x /opt/bin/dual-monitor.sh ];then
#	/opt/bin/dual-monitor.sh
#fi

#my_laptop_external_monitor=$(/usr/bin/xrandr --query | /usr/bin/grep 'HDMI-1')
#if [[ $my_laptop_external_monitor != *disconnected* ]]; then
#	/usr/bin/bspc monitor eDP-1 -d I II III IV V
#	/usr/bin/bspc monitor HDMI-1 -d VI VII VIII IX X
#else
	/usr/bin/bspc monitor -d I II III IV V VI VII VIII IX X
#fi

/usr/bin/bspc config border_width         2
/usr/bin/bspc config window_gap          12

/usr/bin/bspc config split_ratio          0.52
/usr/bin/bspc config borderless_monocle   true
/usr/bin/bspc config gapless_monocle      true

/usr/bin/bspc config border_width 0
/usr/bin/bspc config focus_follows_pointer true

/usr/bin/bash ~/.config/polybar/forest/launch.sh &
/usr/local/bin/picom &
/usr/bin/wmname LG3D &
/usr/bin/flameshot &
#vmware-user-suid-wrapper &

if [ -x /opt/bin/change-background.sh ]; then
	/opt/bin/change-background.sh &
fi

/usr/bin/xsetroot -cursor_name left_ptr &
