#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

#xrandr -s 0
#if [ -x /opt/bin/dual-monitor.sh ];then
#	/opt/bin/dual-monitor.sh
#fi

#my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1')
#if [[ $my_laptop_external_monitor != *disconnected* ]]; then
#	bspc monitor eDP-1 -d I II III IV V
#	bspc monitor HDMI-1 -d VI VII VIII IX X
#else
	bspc monitor -d I II III IV V VI VII VIII IX X
#fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 0
bspc config focus_follows_pointer true

bash ~/.config/polybar/forest/launch.sh &
picom &
wmname LG3D &
flameshot &
#vmware-user-suid-wrapper &

if [ -x /opt/bin/change-background.sh ]; then
	/opt/bin/change-background.sh &
fi

xsetroot -cursor_name left_ptr &
